### ISSUE TITLE
fail to login with my email

### ISSUE THREAD

**Issue by OxCheuk** [gaganode/gaga-server-web-docs#42]
Fail to login with my email address since 2024/2/23 UTC+8.
Have you guys updated the email format filter rule?
error ID: email format error
Email: oxcheuk+meson@gmail.com
Also, there is no method to change my email address without login, which means my account have just been locked!!!
Please fix this problem. Thx!

![image](https://github.com/gaganode/gaga-server-web-docs/assets/161021424/0b580281-a348-40e1-b0d7-5d541ccf6e49)

**Comment by leolikescoding** [comment]
fixed

**Comment by leolikescoding** [comment]
fixed
